# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: E2E Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  chrome:

    runs-on: ubuntu-latest


    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Python
      uses: actions/setup-python@v5.5.0
      with: 
        python-version: 3.13.1

    - name: Test
      run: |
        node --version
        python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:chromium tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token:  ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: Chrome Test Report
        path: logs
  
  firefox:

    runs-on: ubuntu-latest


    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Python
      uses: actions/setup-python@v5.5.0
      with: 
        python-version: 3.13.1

    - name: Test
      run: |
        node --version
        python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:firefox tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token:  ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: Firefox Test Report
        path: logs

